### Manager Development Roadmap
 
The following workshops are 1.5 - 2 hour labs designed for people managers. Come learn a model, converse with people-managers across the company, walk away with a new ideas and skills you can apply immediately. 

 
|Workshop|Description & Learning Objectives|
|--------|--------|
|**Respect in the Workplace**| We want to make GitHub the kind of place where people want to come everyday. And we do that by making it the kind of place that people feel productive and valued. Respect in the Workplace is GitHub’s Harassment Prevention training; As you’re hired or moved into a management role at GitHub, you’ll be required to complete this within your first 90 days. <br> <br> - [Watch this video](https://githubber.tv/github/anti-harassment-training-managers) <br> - [Take this quiz](https://docs.google.com/a/github.com/forms/d/e/1FAIpQLSfKa0d4ZPn6OWQVngVYrfmEEnyYrgOjl4a8RkNBIo5rOKsCrg/viewform?c=0&w=1) |
|**Feedback Fundamentals**| Quick Poll: Would you rather A) never get feedback on your work or how you’re doing? Or B) get lots of feedback and know some of it will be delivered poorly? If you said B - you’re in the majority; Most of us want feedback - we want to be doing our best work everyday. The good news is that delivering effective feedback is a skill that can be learned and perfected with practice. This workshop will provide helpful frameworks and tips and give you a safe space to practice for a real-life upcoming conversation. <br> <br> - Provide and practice a simple framework for giving effective ongoing feedback <br> - Create a safe space for practice <br> - Prepare for an upcoming conversation| 
|**One-on-One 101** | One-on-one meetings with direct reports often feel more hurried and disorganized than they need to be. It’s important to check in regularly with each of your employees (it’s in our GitHub Manager Expectations!), but how can you make the best use of the time? How can you make the meetings more productive and collaborative? <br> <br> - Review why we have 1:1s and introduce formats to experiment with <br> - Group discussion on best practices, tips and questions | 
| **Managing Conflict at Work** | Whether we like to admit it or not, we all struggle with conflict at work. Every day we navigate competing interests, different personalities, and challenging time and resource constraints. Sure, we share the same goals, but we don't always agree on how to achieve them. This workshop is designed to help people-managers at GitHub understand and deal with pressing work challenges. <br> <br> - Deepen understanding of types of conflicts <br> - Review and practice a dialog framework| 
| **Coaching with Presence** | Managers often feel immense pressure to know all the answers, but *deep breath* having all the answers is not your job. GitHub hires super smart people to work together to find the answers -- your job is to facilitate them. This workshop explores a framework for how to be present to our teams, listen and ask powerful questions that help develop your Hubbers and generate great outcomes. <br><br> - Review a framework for coaching <br> - Build skills in active listening and asking powerful questions |
| **Delegating: Planning for Skill & Will** | Delegation is a superpower that can make managers twice as effective, but is often one of the hardest parts of the gig. This workshop is designed to help you match opportunities with your Hubbers’ strengths and help develop them - and free you up - in the process. <br> <br> - Match work that leverages strengths and develops Hubbers <br> - Provide context and clarity for tasks and projects <br> - Provide the right amount of support for troubleshooting and tracking progress|
| **Decision Making** | Every day we make decisions that impact not only us, but our team and GitHub. Making decisions is tough - at GitHub we move fast, and Shipping is one of our core values. That means sometimes we have to call the shots without the full picture or data and often under tight time constraints. So, how do we ensure we’re making the right ones? This workshop explores a framework for stakeholder analysis and context on when and how much you might involve your team in specific decisions. <br> <br> - Learn and apply the RACI framework <br> - Provide and practice the Tell/Sell model for tailoring your approach to the decision at hand |
 
